Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -1,6 +1,3 @@
-# This workflow will install Python dependencies, run tests and lint with a single version of Python
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
-
 name: Python application
 
 on:
@@ -14,26 +11,33 @@ permissions:
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     steps:
     - uses: actions/checkout@v4
+
     - name: Set up Python 3.12.0
       uses: actions/setup-python@v3
       with:
         python-version: "3.12.0"
+
     - name: Install dependencies
       run: |
         make install
-        make run
-        sleep 10
-    - name: Lint with flake8
+
+    - name: Start server and wait
       run: |
-        # stop the build if there are Python syntax errors or undefined names
-        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
-        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
-        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
+        make run &
+        SERVER_PID=$!
+        sleep 10
+
     - name: Test with pytest
       run: |
         pytest
+
+    - name: Kill the server
+      if: always()
+      run: |
+        if [[ -n $SERVER_PID ]]; then
+          kill $SERVER_PID || echo "Server process not found."
+        fi
